"""文字形式存储的品牌资产, 避免 PR 出现二进制 diff."""
from __future__ import annotations

import argparse
import base64
from pathlib import Path
from typing import Final

DR_R_ICON_BASE64: Final[str] = (
    "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAEaklEQVR42u3dwQ2DQAxFwb1TBPXQ"
    "f0HQASevtPafSK8AYzzKKVnX/bySMlseggQASQCQBABJAJAEAEkAkAQASQCQBABJAJAEAEkAkAQA"
    "SQCQBABJAJAEAEkAkAQASQCQBABJAJAEAEkAkAQASQCQBABJAJAEAEkAkAQASQCQBABJAJAEAEkA"
    "kADgIUgAkAQASQCQBABJAJAEAEkAkAQASQCQBABJAJAEAEkAkAQASQCQBABJAJAEAEkAkAQASQCQ"
    "FAqAz//HS+v9q3w/AAAAAcACACAAWAAAAAAACwAAAABgAQAAAAAsAAAAAIAFAAAAALAAAAAAABYA"
    "AAAAwAIAAAAAWAAAAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4"
    "/wCwcwHmEQAAYB4BAADmEQAAYB4BAADmUTcA/DEIAAQAAABAAAAAAAQAAABAAAAAAAQAAABAAAAA"
    "AAQAAJhHAACAeQQAAJhHAACAeQQAAJhHAACAeQQAAJhHAHAw5gEAAByMeQAAAAdjHgAAwMGYBwAA"
    "cDAAAAAAHAwAAAAABwMAAADAwQAAAABwMAAAAAAcDAAAAAAHAwAAAMDBAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANTNk/4BAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAmPB8AAAAAAAAAAAAAAAAYB4AAAAA5gEAAABgHgAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAABwMAAAAAAcDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAADAXAH/8AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMB8AE47EAA4GAAAAAAOBgAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAGT+YAMA/GAIAAAAAAAAAAAA8P4BAAAA8P4BAAAdADh9PgAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAUAAAA57wgAAAAAAAAAAACY"
    "9P4BAAAAAAAAAACA1PcPAAAAAAB6AaDsH8zwjGv3AgABIHg3ABAAfAsAgADgWwAABAAAAEAAyNkR"
    "AAQAAABAABAAJAFAEgAkAEgCgCQASAKAJABIAoAkAEgCgCQASAKAJABIAoAkAEgCgCQASAKAJABI"
    "AoAkAEgCgCQASAKAJABIAoAkAEgCgCQASAKAJABIAoAkAEgCgCQASAKAJABIAoAEAA9BAoAkAEgC"
    "gCQASAKAJABIAoAkAEgCgCQASAKAJABI6tEHUvS5EhlsmiEAAAAASUVORK5CYII="
)


def load_dr_r_icon_bytes() -> bytes:
    """解码 Dr.R 图标的 PNG 字节."""

    return base64.b64decode(DR_R_ICON_BASE64)


def write_dr_r_icon(target_path: str | Path) -> Path:
    """将图标写入指定路径, 并返回 Path 对象."""

    path = Path(target_path)
    path.write_bytes(load_dr_r_icon_bytes())
    return path


def _build_cli() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="生成 Dr.R 图标文件")
    parser.add_argument(
        "--write-icon",
        dest="icon_path",
        type=str,
        default="dr-r-icon.png",
        help="输出图标的路径 (默认: dr-r-icon.png)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_cli()
    args = parser.parse_args(argv)
    path = write_dr_r_icon(args.icon_path)
    print(f"写入图标: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
